import '@/styles/globals.css'
import type {AppProps} from 'next/app'
import {SWRConfig} from "swr";
import {fetcher} from "@/helpers/api";
import Head from "next/head";
import {createTheme, CssBaseline, ThemeProvider} from "@mui/material";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
export default function App({Component, pageProps}: AppProps) {
    const darkTheme = createTheme({
        components:{
            MuiPaper:{
                styleOverrides:{
                    root:{
                        paddingLeft: "10px"
                    }
                }
            }
        },
        palette:{
            mode: "dark"
        }
    })


    return <SWRConfig
        value={{
            fetcher: fetcher
        }}
    >
        <Head>
            <title>PATS!</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <ThemeProvider theme={darkTheme}>
            <CssBaseline/>
            <Component {...pageProps} />
            <ToastContainer style={{ width: "500px" }}/>
        </ThemeProvider>

    </SWRConfig>

}
